import type { VehicleAssumption } from '@goalpilot/contracts';

export const catalogVersion = 'demo-2026-08-v1';

export const illustrativeAssumptions: readonly VehicleAssumption[] = [
  {
    vehicleCode: 'cash',
    displayName: 'Plain cash',
    assumptionVersion: catalogVersion,
    apyBasisPoints: 0,
    effectiveDate: '2026-08-01',
    reviewedDate: '2026-08-23',
    sourceType: 'reviewed_demo_assumption',
    sourceLabel: 'GoalPilot reviewed demonstration model',
    isLive: false,
    liquidityDays: 0,
    lockDays: 0,
    minimumCents: 0,
    enabled: true,
  },
  {
    vehicleCode: 'hysa',
    displayName: 'High-yield savings model',
    assumptionVersion: catalogVersion,
    apyBasisPoints: 400,
    effectiveDate: '2026-08-01',
    reviewedDate: '2026-08-23',
    sourceType: 'reviewed_demo_assumption',
    sourceLabel: 'GoalPilot reviewed demonstration model',
    isLive: false,
    liquidityDays: 1,
    lockDays: 0,
    minimumCents: 0,
    enabled: true,
  },
  {
    vehicleCode: 'cd_ladder',
    displayName: 'Certificate ladder model',
    assumptionVersion: catalogVersion,
    apyBasisPoints: 450,
    effectiveDate: '2026-08-01',
    reviewedDate: '2026-08-23',
    sourceType: 'reviewed_demo_assumption',
    sourceLabel: 'GoalPilot reviewed demonstration model',
    isLive: false,
    liquidityDays: 180,
    lockDays: 180,
    minimumCents: 50_000,
    enabled: true,
  },
  {
    vehicleCode: 'treasury_ladder',
    displayName: 'Treasury-bill ladder model',
    assumptionVersion: catalogVersion,
    apyBasisPoints: 425,
    effectiveDate: '2026-08-01',
    reviewedDate: '2026-08-23',
    sourceType: 'reviewed_demo_assumption',
    sourceLabel: 'GoalPilot reviewed demonstration model',
    isLive: false,
    liquidityDays: 91,
    lockDays: 91,
    minimumCents: 10_000,
    enabled: true,
  },
] as const;
